# building stage
FROM python:3.12.8-slim-bookworm as builder
COPY requirements.txt /tmp
RUN /usr/bin/apt update && /usr/bin/apt upgrade --yes && \
    /usr/bin/apt install gcc g++ clang gfortran flang-16 libopenblas-dev cmake cargo texlive-full pandoc --yes && \
    /usr/bin/apt autoremove --yes && /usr/bin/apt clean && /usr/sbin/useradd -md /home/notebook -s /bin/bash notebook
USER notebook
RUN /usr/local/bin/python3 -m venv /home/notebook/jupyter && /usr/bin/mkdir /home/notebook/data && \
    /bin/bash -c "source /home/notebook/jupyter/bin/activate ; /usr/local/bin/pip install --upgrade pip ; \
    /home/notebook/jupyter/bin/pip install -r /tmp/requirements.txt" && \
    /usr/bin/mkdir /home/notebook/.jupyter
COPY --chown=notebook jupyter_server_config.json /home/notebook/.jupyter

# final stage
FROM python:3.12.8-slim-bookworm
LABEL org.opencontainers.image.authors="Jose Angel de Bustos Perez <jadebustos@gmail.com>"
LABEL org.opencontainers.image.description="Jupyter Notebook"
LABEL org.opencontainers.image.licenses="GPL-3.0-or-later"
LABEL org.opencontainers.image.revision="1.0"
RUN /usr/sbin/useradd -md /home/notebook -s /bin/bash notebook && \
    /usr/bin/mkdir -p /home/notebook/data && /usr/bin/chown -R notebook: /home/notebook
COPY --chown=notebook --from=builder /home/notebook/  /home/notebook/
COPY runme.sh /
EXPOSE 8888
USER notebook
WORKDIR /home/notebook
ENTRYPOINT ["/runme.sh"]
